name: phc_lab
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  flutter: 
    sdk: flutter
  get: ^4.6.5
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.0.15
  cached_network_image: ^3.2.1
  flutter_svg: ^2.0.8
  pin_code_fields: ^8.0.1
  flutter_rating_bar: ^4.0.0
  intl: ^0.18.0
  permission_handler: ^11.0.1
  images_picker: ^1.2.11
  firebase_core: ^2.23.0
  firebase_auth: ^4.14.1
  cloud_firestore: ^4.13.2
  firebase_storage: ^11.5.2
  pdf: ^3.10.4
  printing: ^5.11.0
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  flutter_native_splash: ^2.3.6

flutter_native_splash:
  image: assets/images/splash.png
  color: "#0860C7"
  fullscreen: true

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/

  fonts:
    - family: Raleway
      fonts: 
        - asset: assets/fonts/RalewayRomanBold.ttf
          weight: 700
        - asset: assets/fonts/RalewayBold.ttf
          weight: 700
        - asset: assets/fonts/RalewayMedium.ttf
          weight: 500
        - asset: assets/fonts/RalewaySemiBold.ttf
          weight: 600
        - asset: assets/fonts/RalewayRegular.ttf
          weight: 400
        - asset: assets/fonts/RalewayRomanMedium.ttf
          weight: 500
        - asset: assets/fonts/RalewayRomanRegular.ttf
          weight: 400
        - asset: assets/fonts/RalewayRomanSemiBold.ttf
          weight: 600
    - family: SF Pro Display
      fonts: 
        - asset: assets/fonts/SFProDisplayRegular.ttf
          weight: 400
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterBlackItalic.ttf
          weight: 900
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
